@Api_HostAddress = http://localhost:5092/api

###Crear una nueva especialidad

POST {{Api_HostAddress}}/specialties
Content-Type: application/json

{
  "name": "Test especialidad",
  "description": "Descripción de la especialidad de prueba"
}
